#encoding=utf-8
"""
Created on 2016/8/10 14:30
author: iKexinLL
"""

a = '''
KPI_VALUE1,       --BY5001:移动电话客户省际漫游出访通话量合计 （通话次数）
KPI_VALUE2,       --BY5101:1、主叫合计    （通话次数）
KPI_VALUE3,       --BY5111:  主叫漫游地通话合计   （通话次数）
KPI_VALUE4,       --BY5121:  省内长途主叫通话合计    （通话次数）
KPI_VALUE5,       --BY5131:  省际长途主叫通话合计    （通话次数）
KPI_VALUE6,       --BY5141:  港澳台长途主叫通话合计   （通话次数）
KPI_VALUE7,       --BY5151:  国际长途主叫通话合计  （通话次数）
KPI_VALUE8,       --BY5201:2、主叫构成合计  （通话次数）
KPI_VALUE9,       --BY5301:去本公司移动合计  （通话次数）
KPI_VALUE10,      --BY5311:其中：漫游地通话  （通话次数）
KPI_VALUE11,      --BY5321:      省内通话  （通话次数）
KPI_VALUE12,      --BY5331:      省际通话  （通话次数）
KPI_VALUE13,      --BY5801:去中国铁通固定合计 （通话次数）
KPI_VALUE14,      --BY5811:其中：漫游地通话  （通话次数）
KPI_VALUE15,      --BY5821:      省内通话  （通话次数）
KPI_VALUE16,      --BY5831:      省际通话  （通话次数）
KPI_VALUE17,      --BY5501:去中国联通移动合计 （通话次数）
KPI_VALUE18,      --BY5511:其中：漫游地通话  （通话次数）
KPI_VALUE19,      --BY5521:      省内通话  （通话次数）
KPI_VALUE20,      --BY5531:      省际通话  （通话次数）
KPI_VALUE21,      --BY5701:去中国联通固定合计 （通话次数）
KPI_VALUE22,      --BY5711:其中：漫游地通话  （通话次数）
KPI_VALUE23,      --BY5721:      省内通话  （通话次数）
KPI_VALUE24,      --BY5731:      省际通话  （通话次数）
KPI_VALUE25,      --BY5601:去中国电信移动合计 （通话次数）
KPI_VALUE26,      --BY5611:其中：漫游地通话  （通话次数）
KPI_VALUE27,      --BY5621:      省内通话  （通话次数）
KPI_VALUE28,      --BY5631:      省际通话  （通话次数）
KPI_VALUE29,      --BY5401:去中国电信固定合计 （通话次数）
KPI_VALUE30,      --BY5411:其中：漫游地通话  （通话次数）
KPI_VALUE31,      --BY5421:      省内通话  （通话次数）
KPI_VALUE32,      --BY5431:      省际通话  （通话次数）
KPI_VALUE33,      --BY5901:其他去话  （通话次数）
KPI_VALUE34,      --BY6101:3、被叫合计    （通话次数）
KPI_VALUE35,      --BY6151:其中：漫游地来话合计  （通话次数）
KPI_VALUE36,      --BY6161:      省内来话合计  （通话次数）
KPI_VALUE37,      --BY6171:      省际来话合计  （通话次数）
KPI_VALUE38,      --BY6181:      国际来话合计  （通话次数）
KPI_VALUE39,      --BY6191:      港澳台来话合计 （通话次数）
KPI_VALUE40,      --BY6201:4、被叫构成合计  （通话次数）
KPI_VALUE41,      --BY6301:其中：本公司移动来话合计  （通话次数）
KPI_VALUE42,      --BY6801:      中国铁通固定来话合计  （通话次数）
KPI_VALUE43,      --BY6501:      中国联通移动来话合计  （通话次数）
KPI_VALUE44,      --BY6701:      中国联通固定来话合计  （通话次数）
KPI_VALUE45,      --BY6601:      中国电信移动来话合计  （通话次数）
KPI_VALUE46,      --BY6401:      中国电信固定来话合计  （通话次数）
KPI_VALUE47,      --BY6901:      其他来话  （通话次数）
KPI_VALUE48,      --BY5007:移动电话客户省际漫游出访通话量合计  (VO-LTE通话次数)
KPI_VALUE49,      --BY5107:1、主叫合计     (VO-LTE通话次数)
KPI_VALUE50,      --BY5117:  主叫漫游地通话合计    (VO-LTE通话次数)
KPI_VALUE51,      --BY5127:  省内长途主叫通话合计     (VO-LTE通话次数)
KPI_VALUE52,      --BY5137:  省际长途主叫通话合计     (VO-LTE通话次数)
KPI_VALUE53,      --BY5147:  港澳台长途主叫通话合计    (VO-LTE通话次数)
KPI_VALUE54,      --BY5157:  国际长途主叫通话合计   (VO-LTE通话次数)
KPI_VALUE55,      --BY5207:2、主叫构成合计   (VO-LTE通话次数)
KPI_VALUE56,      --BY5307:去本公司移动合计   (VO-LTE通话次数)
KPI_VALUE57,      --BY5317:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE58,      --BY5327:      省内通话   (VO-LTE通话次数)
KPI_VALUE59,      --BY5337:      省际通话   (VO-LTE通话次数)
KPI_VALUE60,      --BY5807:去中国铁通固定合计  (VO-LTE通话次数)
KPI_VALUE61,      --BY5817:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE62,      --BY5827:      省内通话   (VO-LTE通话次数)
KPI_VALUE63,      --BY5837:      省际通话   (VO-LTE通话次数)
KPI_VALUE64,      --BY5507:去中国联通移动合计  (VO-LTE通话次数)
KPI_VALUE65,      --BY5517:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE66,      --BY5527:      省内通话   (VO-LTE通话次数)
KPI_VALUE67,      --BY5537:      省际通话   (VO-LTE通话次数)
KPI_VALUE68,      --BY5707:去中国联通固定合计  (VO-LTE通话次数)
KPI_VALUE69,      --BY5717:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE70,      --BY5727:      省内通话   (VO-LTE通话次数)
KPI_VALUE71,      --BY5737:      省际通话   (VO-LTE通话次数)
KPI_VALUE72,      --BY5607:去中国电信移动合计  (VO-LTE通话次数)
KPI_VALUE73,      --BY5617:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE74,      --BY5627:      省内通话   (VO-LTE通话次数)
KPI_VALUE75,      --BY5637:      省际通话   (VO-LTE通话次数)
KPI_VALUE76,      --BY5407:去中国电信固定合计  (VO-LTE通话次数)
KPI_VALUE77,      --BY5417:其中：漫游地通话   (VO-LTE通话次数)
KPI_VALUE78,      --BY5427:      省内通话   (VO-LTE通话次数)
KPI_VALUE79,      --BY5437:      省际通话   (VO-LTE通话次数)
KPI_VALUE80,      --BY5907:其他去话   (VO-LTE通话次数)
KPI_VALUE81,      --BY6107:3、被叫合计     (VO-LTE通话次数)
KPI_VALUE82,      --BY6157:其中：漫游地来话合计   (VO-LTE通话次数)
KPI_VALUE83,      --BY6167:      省内来话合计   (VO-LTE通话次数)
KPI_VALUE84,      --BY6177:      省际来话合计   (VO-LTE通话次数)
KPI_VALUE85,      --BY6187:      国际来话合计   (VO-LTE通话次数)
KPI_VALUE86,      --BY6197:      港澳台来话合计  (VO-LTE通话次数)
KPI_VALUE87,      --BY6207:4、被叫构成合计   (VO-LTE通话次数)
KPI_VALUE88,      --BY6307:其中：本公司移动来话合计   (VO-LTE通话次数)
KPI_VALUE89,      --BY6807:      中国铁通固定来话合计   (VO-LTE通话次数)
KPI_VALUE90,      --BY6507:      中国联通移动来话合计   (VO-LTE通话次数)
KPI_VALUE91,      --BY6707:      中国联通固定来话合计   (VO-LTE通话次数)
KPI_VALUE92,      --BY6607:      中国电信移动来话合计   (VO-LTE通话次数)
KPI_VALUE93,      --BY6407:      中国电信固定来话合计   (VO-LTE通话次数)
KPI_VALUE94,      --BY6907:      其他来话   (VO-LTE通话次数)
KPI_VALUE95,      --BY5002:移动电话客户省际漫游出访通话量合计  (基本计费时长)
KPI_VALUE96,      --BY5102:1、主叫合计     (基本计费时长)
KPI_VALUE97,      --BY5112:  主叫漫游地通话合计    (基本计费时长)
KPI_VALUE98,      --BY5122:  省内长途主叫通话合计     (基本计费时长)
KPI_VALUE99,      --BY5132:  省际长途主叫通话合计     (基本计费时长)
KPI_VALUE100,     --BY5142:  港澳台长途主叫通话合计    (基本计费时长)
KPI_VALUE101,     --BY5152:  国际长途主叫通话合计   (基本计费时长)
KPI_VALUE102,     --BY5202:2、主叫构成合计   (基本计费时长)
KPI_VALUE103,     --BY5302:去本公司移动合计   (基本计费时长)
KPI_VALUE104,     --BY5312:其中：漫游地通话   (基本计费时长)
KPI_VALUE105,     --BY5322:      省内通话   (基本计费时长)
KPI_VALUE106,     --BY5332:      省际通话   (基本计费时长)
KPI_VALUE107,     --BY5802:去中国铁通固定合计  (基本计费时长)
KPI_VALUE108,     --BY5812:其中：漫游地通话   (基本计费时长)
KPI_VALUE109,     --BY5822:      省内通话   (基本计费时长)
KPI_VALUE110,     --BY5832:      省际通话   (基本计费时长)
KPI_VALUE111,     --BY5502:去中国联通移动合计  (基本计费时长)
KPI_VALUE112,     --BY5512:其中：漫游地通话   (基本计费时长)
KPI_VALUE113,     --BY5522:      省内通话   (基本计费时长)
KPI_VALUE114,     --BY5532:      省际通话   (基本计费时长)
KPI_VALUE115,     --BY5702:去中国联通固定合计  (基本计费时长)
KPI_VALUE116,     --BY5712:其中：漫游地通话   (基本计费时长)
KPI_VALUE117,     --BY5722:      省内通话   (基本计费时长)
KPI_VALUE118,     --BY5732:      省际通话   (基本计费时长)
KPI_VALUE119,     --BY5602:去中国电信移动合计  (基本计费时长)
KPI_VALUE120,     --BY5612:其中：漫游地通话   (基本计费时长)
KPI_VALUE121,     --BY5622:      省内通话   (基本计费时长)
KPI_VALUE122,     --BY5632:      省际通话   (基本计费时长)
KPI_VALUE123,     --BY5402:去中国电信固定合计  (基本计费时长)
KPI_VALUE124,     --BY5412:其中：漫游地通话   (基本计费时长)
KPI_VALUE125,     --BY5422:      省内通话   (基本计费时长)
KPI_VALUE126,     --BY5432:      省际通话   (基本计费时长)
KPI_VALUE127,     --BY5902:其他去话   (基本计费时长)
KPI_VALUE128,     --BY6102:3、被叫合计     (基本计费时长)
KPI_VALUE129,     --BY6152:其中：漫游地来话合计   (基本计费时长)
KPI_VALUE130,     --BY6162:      省内来话合计   (基本计费时长)
KPI_VALUE131,     --BY6172:      省际来话合计   (基本计费时长)
KPI_VALUE132,     --BY6182:      国际来话合计   (基本计费时长)
KPI_VALUE133,     --BY6192:      港澳台来话合计  (基本计费时长)
KPI_VALUE134,     --BY6202:4、被叫构成合计   (基本计费时长)
KPI_VALUE135,     --BY6302:其中：本公司移动来话合计   (基本计费时长)
KPI_VALUE136,     --BY6802:      中国铁通固定来话合计   (基本计费时长)
KPI_VALUE137,     --BY6502:      中国联通移动来话合计   (基本计费时长)
KPI_VALUE138,     --BY6702:      中国联通固定来话合计   (基本计费时长)
KPI_VALUE139,     --BY6602:      中国电信移动来话合计   (基本计费时长)
KPI_VALUE140,     --BY6402:      中国电信固定来话合计   (基本计费时长)
KPI_VALUE141,     --BY6902:      其他来话   (基本计费时长)
KPI_VALUE142,     --BY5008:移动电话客户省际漫游出访通话量合计  (VO-LTE基本计费时长）
KPI_VALUE143,     --BY5108:1、主叫合计     (VO-LTE基本计费时长)
KPI_VALUE144,     --BY5118:  主叫漫游地通话合计    (VO-LTE基本计费时长)
KPI_VALUE145,     --BY5128:  省内长途主叫通话合计     (VO-LTE基本计费时长)
KPI_VALUE146,     --BY5138:  省际长途主叫通话合计     (VO-LTE基本计费时长)
KPI_VALUE147,     --BY5148:  港澳台长途主叫通话合计    (VO-LTE基本计费时长)
KPI_VALUE148,     --BY5158:  国际长途主叫通话合计   (VO-LTE基本计费时长)
KPI_VALUE149,     --BY5208:2、主叫构成合计   (VO-LTE基本计费时长)
KPI_VALUE150,     --BY5308:去本公司移动合计   (VO-LTE基本计费时长)
KPI_VALUE151,     --BY5318:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE152,     --BY5328:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE153,     --BY5338:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE154,     --BY5808:去中国铁通固定合计  (VO-LTE基本计费时长)
KPI_VALUE155,     --BY5818:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE156,     --BY5828:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE157,     --BY5838:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE158,     --BY5508:去中国联通移动合计  (VO-LTE基本计费时长)
KPI_VALUE159,     --BY5518:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE160,     --BY5528:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE161,     --BY5538:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE162,     --BY5708:去中国联通固定合计  (VO-LTE基本计费时长)
KPI_VALUE163,     --BY5718:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE164,     --BY5728:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE165,     --BY5738:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE166,     --BY5608:去中国电信移动合计  (VO-LTE基本计费时长)
KPI_VALUE167,     --BY5618:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE168,     --BY5628:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE169,     --BY5638:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE170,     --BY5408:去中国电信固定合计  (VO-LTE基本计费时长)
KPI_VALUE171,     --BY5418:其中：漫游地通话   (VO-LTE基本计费时长)
KPI_VALUE172,     --BY5428:      省内通话   (VO-LTE基本计费时长)
KPI_VALUE173,     --BY5438:      省际通话   (VO-LTE基本计费时长)
KPI_VALUE174,     --BY5908:其他去话   (VO-LTE基本计费时长)
KPI_VALUE175,     --BY6108:3、被叫合计     (VO-LTE基本计费时长)
KPI_VALUE176,     --BY6158:其中：漫游地来话合计   (VO-LTE基本计费时长)
KPI_VALUE177,     --BY6168:      省内来话合计   (VO-LTE基本计费时长)
KPI_VALUE178,     --BY6178:      省际来话合计   (VO-LTE基本计费时长)
KPI_VALUE179,     --BY6188:      国际来话合计   (VO-LTE基本计费时长)
KPI_VALUE180,     --BY6198:      港澳台来话合计  (VO-LTE基本计费时长)
KPI_VALUE181,     --BY6208:4、被叫构成合计   (VO-LTE基本计费时长)
KPI_VALUE182,     --BY6308:其中：本公司移动来话合计   (VO-LTE基本计费时长)
KPI_VALUE183,     --BY6808:      中国铁通固定来话合计   (VO-LTE基本计费时长)
KPI_VALUE184,     --BY6508:      中国联通移动来话合计   (VO-LTE基本计费时长)
KPI_VALUE185,     --BY6708:      中国联通固定来话合计   (VO-LTE基本计费时长)
KPI_VALUE186,     --BY6608:      中国电信移动来话合计   (VO-LTE基本计费时长)
KPI_VALUE187,     --BY6408:      中国电信固定来话合计   (VO-LTE基本计费时长)
KPI_VALUE188,     --BY6908:      其他来话   (VO-LTE基本计费时长)
KPI_VALUE189,     --BY5003:移动电话客户省际漫游出访通话量合计 (长途计费时长)
KPI_VALUE190,     --BY5103:1、主叫合计    (长途计费时长)
KPI_VALUE191,     --BY5143:  港澳台长途主叫通话合计   (长途计费时长)
KPI_VALUE192,     --BY5153:  国际长途主叫通话合计  (长途计费时长)
KPI_VALUE193,     --BY5203:2、主叫构成合计  (长途计费时长)
KPI_VALUE194,     --BY5903:其他去话  (长途计费时长)
KPI_VALUE195,     --BY5009:移动电话客户省际漫游出访通话量合计  (VO-LTE长途计费时
KPI_VALUE196,     --BY5109:1、主叫合计     (VO-LTE长途计费时长)
KPI_VALUE197,     --BY5149:  港澳台长途主叫通话合计    (VO-LTE长途计费时长)
KPI_VALUE198,     --BY5159:  国际长途主叫通话合计   (VO-LTE长途计费时长)
KPI_VALUE199,     --BY5209:2、主叫构成合计   (VO-LTE长途计费时长)
KPI_VALUE200,     --BY5909:其他去话   (VO-LTE长途计费时长)
KPI_VALUE201,     --AA1201:移动非漫游本地计费时长
KPI_VALUE202,     --AA1202:移动非漫游传统国内长途计费时长
KPI_VALUE203,     --AA1203:移动非漫游传统国际长途计费时长
KPI_VALUE204,     --AA1204:移动非漫游传统港澳台长途计费时长
KPI_VALUE205,     --AA1205:移动国内漫游计费时长
KPI_VALUE206,     --AA1206:移动国际漫游计费时长
KPI_VALUE207,     --AA1207:移动港澳台漫游计费时长
KPI_VALUE208,     --AA1208:移动国内IP电话计费时长
KPI_VALUE209,     --AA1209:移动国际IP电话计费时长
KPI_VALUE210,     --AA1210:移动港澳台IP电话计费时长
KPI_VALUE211,     --AA1211:移动可视电话计费时长
KPI_VALUE212,     --BK1002:可视电话合计（基本计费时长）
KPI_VALUE213,     --BK2002:可视电话非漫游合计（基本计费时长）
KPI_VALUE214,     --BK2102:主叫合计（基本计费时长）
KPI_VALUE215,     --BK2112:本地主叫通话合计（基本计费时长）
KPI_VALUE216,     --BK2122:省内长途主叫通话合计（基本计费时长）
KPI_VALUE217,     --BK2132:省际长途主叫通话合计（基本计费时长）
KPI_VALUE218,     --BK2142:港澳台长途主叫通话合计（基本计费时长）
KPI_VALUE219,     --BK2152:国际长途主叫通话合计（基本计费时长）
KPI_VALUE220,     --BK2202:被叫合计（基本计费时长）
KPI_VALUE221,     --BK3002:可视电话国内漫游出访合计（基本计费时长）
KPI_VALUE222,     --BK1003:可视电话合计（长途计费时长）
KPI_VALUE223,     --BK2003:可视电话非漫游合计（长途计费时长）
KPI_VALUE224,     --BK2103:主叫合计（长途计费时长）
KPI_VALUE225,     --BK2123:省内长途主叫通话合计（长途计费时长）
KPI_VALUE226,     --BK2133:省际长途主叫通话合计（长途计费时长）
KPI_VALUE227,     --BK2143:港澳台长途主叫通话合计（长途计费时长）
KPI_VALUE228,     --BK2153:国际长途主叫通话合计（长途计费时长）
KPI_VALUE229      --BK3003:可视电话国内漫游出访合计（长途计费时长）
'''

b = '''
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND OLD_ROAM_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='50' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70')  THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4'  THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN('5','6','7') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70')  THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND OLD_ROAM_TYPE='4' AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='50'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70') AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61')  THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN('5','6','7')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42')AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40'AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70') AND MNS_TYPE ='6' IN('60','61') THEN A.CDR_NUMS ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND OLD_ROAM_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.OLD_ROAM_TYPE='4' AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='0' AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82')AND MNS_TYPE ='6' IN('60','61') AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82') AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42') AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='0'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='2'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='3'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN ('5','6','7')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02' AND A.OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='10'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='50'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('20','21','81','82')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER ='80'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('41','42')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER='40'AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='4' AND A.OPPOSE_DEALER IN('0','30','31','60','70')AND MNS_TYPE ='6' IN('60','61') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7') AND A.CALL_TYPE='01'THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN('5','6','7')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4'AND A.OPPOSE_DEALER IN('0','30','31','60','70')AND A.FEE_TYPE='3'THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7') AND MNS_TYPE ='6' IN('60','61')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7')AND MNS_TYPE ='6' IN('60','61')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE='4'AND MNS_TYPE ='6' IN('60','61')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE IN('5','6','7')AND MNS_TYPE ='6' IN('60','61')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4' AND A.FEE_TYPE in('4','5','6','7')AND MNS_TYPE ='6' IN('60','61')THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND OLD_ROAM_TYPE='4'AND A.OPPOSE_DEALER IN('0','30','31','60','70')AND MNS_TYPE ='6' IN('60','61')AND A.FEE_TYPE='3'THEN CEILING(RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE ='0' AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE IN('2','3') AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') AND A.CALL_TYPE='01'THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE IN('5','6','7') AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE='4' AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.OLD_ROAM_TYPE IN('2','3','4')AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') AND A.CALL_TYPE IN('01','02')THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03')AND A.OLD_ROAM_TYPE IN('6','7','5')AND(A.MMM_TYPE!='02' OR A.IS_MULTIMEDIA!='1') AND A.CALL_TYPE IN('01','02') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE NOT IN ('02','03') AND A.OLD_ROAM_TYPE='8'  AND A.CALL_TYPE IN('01','02') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE='03'AND A.OLD_ROAM_TYPE ='0' AND A.CALL_TYPE='01'AND A.FEE_TYPE IN('0','2','3')  THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE='03'AND  A.FEE_TYPE IN('5','6','7')  THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.LAND_TYPE='03'AND  A.FEE_TYPE ='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02'AND  A.IS_MULTIMEDIA ='1'AND A.OLD_ROAM_TYPE='0' AND A.CALL_TYPE IN('01','02')THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.OLD_ROAM_TYPE='0'  THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.OLD_ROAM_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE='2' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE='3' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE='4' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE IN('5','6','7') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='0' THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE IN('2','3') THEN A.CALL_TIMES ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE !='0'THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.OLD_ROAM_TYPE='0' THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0' THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01' AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE='2' THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE='3' THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE='4' THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='01'AND A.OLD_ROAM_TYPE='0'AND A.FEE_TYPE IN('5','6','7') THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
SUM(CASE WHEN A.MMM_TYPE='02' AND IS_MULTIMEDIA='1' AND A.CALL_TYPE='02'AND A.OLD_ROAM_TYPE='0' AND A.FEE_TYPE IN('5','6','7') THEN CEILING(A.RESV_NUM2/10) ELSE NULL END),
'''

d = {}

at = a.split('\n')[1:-1] #去除换行或者空值
at[-1] = 'KPI_VALUE229,      --BK3003:可视电话国内漫游出访合计（长途计费时长）'

bt = b.split('END),')
for i in range(len(bt[:-1])):
    bt[i] = bt[i] + 'END),'

for i in range(len(at)):
    te = at[i].split(',')
    d[te[0]] = [bt[i].replace('\n',''),te[1].replace(' ','')]

print(d['KPI_VALUE209'])